import React, { createContext, useContext, useEffect, useState } from 'react';

const translations = {
  id: {
    app_name: "AUTOLIVE",
    welcome: "Selamat Datang",
    logout: "Keluar",
    dashboard: "Dashboard",
    viral_filter: "Filter Video Viral",
    downloader: "Downloader",
    editor: "Editor",
    auto_upload: "Upload Otomatis",
    scheduler: "Penjadwalan",
    settings: "Pengaturan",
    login: "Masuk",
    login_with_google: "Masuk dengan Google",
    logging_in: "Memproses...",
    auto_content: "Platform Upload Konten Otomatis",
    features_title: "Fitur Unggulan",
    register: "Daftar Sekarang",
    email: "Email",
    password: "Password",
    forgot_password: "Lupa password?",
    no_account: "Belum punya akun?",
    register_now: "Daftar Sekarang",
    upgrade_pro: "Upgrade ke Pro",
    upgrade_premium: "Upgrade ke Premium",
    free: "Gratis",
    pro: "Pro",
    premium: "Premium",
    active: "Aktif",
    select_plan: "Pilih Paket",
    website_settings: "Pengaturan Website",
    user_management: "Manajemen User",
    change_logo: "Ganti Logo",
    save_settings: "Simpan Pengaturan",
    primary_color: "Warna Utama",
    secondary_color: "Warna Sekunder",
    contact_email: "Email Kontak",
    users: "Pengguna",
    videos: "Video",
    schedules: "Jadwal",
    payment: "Pembayaran",
    total: "Total",
    bank_transfer: "Transfer Bank",
    dana: "DANA",
    paypal: "PayPal",
    minipay: "MiniPay",
    full_name: "Nama Lengkap",
    phone: "No. Telepon",
    confirm_password: "Konfirmasi Password",
    verification_code: "Kode Verifikasi",
    send_code: "Kirim Kode",
    enter_code: "Masukkan kode 6 digit",
    code_sent: "Kode telah dikirim ke email Anda",
    already_have_account: "Sudah punya akun?",
    login_here: "Login di sini",
    quick_access: "Akses Cepat",
    videos_uploaded: "Video Diupload",
    total_views: "Total Tayangan",
    active_schedules: "Jadwal Aktif",
    upgrade_to_access: "Upgrade untuk akses fitur ini",
    account_expired: "Masa aktif akun telah berakhir",
    welcome_admin: "Selamat Datang Admin!",
    select_access: "Silakan pilih akses yang akan Anda gunakan",
    admin_access: "Akses Admin",
    admin_access_desc: "Akses penuh ke Panel Admin",
    premium_access: "Akses Premium",
    premium_access_desc: "Akses semua fitur lengkap",
    pro_access: "Akses Pro",
    pro_access_desc: "Akses semua fitur kecuali jadwal",
    free_access: "Akses Free Trial",
    free_access_desc: "Akses fitur terbatas 1 hari",
    email_exists: "Email sudah terdaftar",
    upgrade_not_allowed: "Akun dengan status PRO/PREMIUM tidak dapat mendaftar sebagai FREE",
    verification_failed: "Kode verifikasi salah"
  },
  en: {
    app_name: "AUTOLIVE",
    welcome: "Welcome",
    logout: "Logout",
    dashboard: "Dashboard",
    viral_filter: "Viral Video Filter",
    downloader: "Downloader",
    editor: "Editor",
    auto_upload: "Auto Upload",
    scheduler: "Scheduler",
    settings: "Settings",
    login: "Login",
    login_with_google: "Login with Google",
    logging_in: "Logging in...",
    auto_content: "Auto Content Upload Platform",
    features_title: "Features",
    register: "Register Now",
    email: "Email",
    password: "Password",
    forgot_password: "Forgot password?",
    no_account: "Don't have an account?",
    register_now: "Register Now",
    upgrade_pro: "Upgrade to Pro",
    upgrade_premium: "Upgrade to Premium",
    free: "Free",
    pro: "Pro",
    premium: "Premium",
    active: "Active",
    select_plan: "Select Plan",
    website_settings: "Website Settings",
    user_management: "User Management",
    change_logo: "Change Logo",
    save_settings: "Save Settings",
    primary_color: "Primary Color",
    secondary_color: "Secondary Color",
    contact_email: "Contact Email",
    users: "Users",
    videos: "Videos",
    schedules: "Schedules",
    payment: "Payment",
    total: "Total",
    bank_transfer: "Bank Transfer",
    dana: "DANA",
    paypal: "PayPal",
    minipay: "MiniPay",
    full_name: "Full Name",
    phone: "Phone Number",
    confirm_password: "Confirm Password",
    verification_code: "Verification Code",
    send_code: "Send Code",
    enter_code: "Enter 6-digit code",
    code_sent: "Code has been sent to your email",
    already_have_account: "Already have an account?",
    login_here: "Login here",
    quick_access: "Quick Access",
    videos_uploaded: "Videos Uploaded",
    total_views: "Total Views",
    active_schedules: "Active Schedules",
    upgrade_to_access: "Upgrade to access this feature",
    account_expired: "Account has expired",
    welcome_admin: "Welcome Admin!",
    select_access: "Please select the access you want to use",
    admin_access: "Admin Access",
    admin_access_desc: "Full access to Admin Panel",
    premium_access: "Premium Access",
    premium_access_desc: "Full feature access",
    pro_access: "Pro Access",
    pro_access_desc: "All features except scheduler",
    free_access: "Free Trial Access",
    free_access_desc: "Limited features for 1 day",
    email_exists: "Email already registered",
    upgrade_not_allowed: "PRO/PREMIUM accounts cannot register as FREE",
    verification_failed: "Verification code is incorrect"
  },
  zh: {
    app_name: "AUTOLIVE",
    welcome: "欢迎",
    logout: "退出",
    dashboard: "仪表板",
    viral_filter: "病毒视频过滤器",
    downloader: "下载器",
    editor: "编辑器",
    auto_upload: "自动上传",
    scheduler: "调度程序",
    settings: "设置",
    login: "登录",
    login_with_google: "使用谷歌登录",
    logging_in: "登录中...",
    auto_content: "自动内容上传平台",
    features_title: "功能特点",
    register: "立即注册",
    email: "电子邮件",
    password: "密码",
    forgot_password: "忘记密码？",
    no_account: "还没有账户？",
    register_now: "立即注册",
    upgrade_pro: "升级到专业版",
    upgrade_premium: "升级到高级版",
    free: "免费",
    pro: "专业",
    premium: "高级",
    active: "激活",
    select_plan: "选择套餐",
    website_settings: "网站设置",
    user_management: "用户管理",
    change_logo: "更换标志",
    save_settings: "保存设置",
    primary_color: "主色",
    secondary_color: "辅色",
    contact_email: "联系邮箱",
    users: "用户",
    videos: "视频",
    schedules: "日程",
    payment: "支付",
    total: "总计",
    bank_transfer: "银行转账",
    dana: "DANA",
    paypal: "PayPal",
    minipay: "MiniPay",
    full_name: "全名",
    phone: "电话号码",
    confirm_password: "确认密码",
    verification_code: "验证码",
    send_code: "发送验证码",
    enter_code: "输入6位验证码",
    code_sent: "验证码已发送到您的邮箱",
    already_have_account: "已有账户？",
    login_here: "在此登录",
    quick_access: "快速访问",
    videos_uploaded: "已上传视频",
    total_views: "总观看次数",
    active_schedules: "活跃日程",
    upgrade_to_access: "升级以访问此功能",
    account_expired: "账户已过期",
    welcome_admin: "欢迎管理员！",
    select_access: "请选择您要使用的访问权限",
    admin_access: "管理员访问",
    admin_access_desc: "完全访问管理面板",
    premium_access: "高级访问",
    premium_access_desc: "完整功能访问",
    pro_access: "专业访问",
    pro_access_desc: "除调度器外的所有功能",
    free_access: "免费试用访问",
    free_access_desc: "1天有限功能",
    email_exists: "邮箱已注册",
    upgrade_not_allowed: "专业/高级账户不能注册为免费账户",
    verification_failed: "验证码错误"
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('app_language');
    return (saved === 'id' || saved === 'en' || saved === 'zh') ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => translations[language][key] || key;
  const changeLanguage = (lang) => { if (translations[lang]) setLanguage(lang); };

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};
